#!/usr/bin/env zsh

if [[ ! -d $USER_GIT_ROOT/binaryen ]]; then
    git clone git@github.com:WebAssembly/binaryen.git $USER_GIT_ROOT/binaryen
fi

cd $USER_GIT_ROOT/binaryen
git clean -fdx
mkdir build
cd build

cmake \
    -DCMAKE_INSTALL_PREFIX=$USER_GIT_ROOT/binaryen/release \
    ..

make -j$(nproc) install

