#!/usr/bin/env zsh

WD=$USER_GIT_ROOT/llvm
if [[ ! -d $WD ]]; then
    git clone \
        --depth 1 \
        --single-branch \
        --branch release_40 \
        git@github.com:llvm-mirror/llvm.git $WD
    git clone \
        --depth 1 \
        --single-branch \
        --branch release_40 \
        git@github.com:llvm-mirror/clang.git $WD/tools/clang
fi

cd $WD
[[ $YES -eq 0 ]] && read REPLY"?clean $WD? [y|N] "
[[ $YES -eq 1 || $REPLY =~ ^[Yy]$ ]] && git clean -fdx
mkdir {build,release}
cd build

cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$WD/release \
    -DLLVM_ENABLE_RTTI=On \
    -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -G "Unix Makefiles" \
    ..
make -j${NPROC:-1} install

