#!/bin/zsh

export BOOST_VER=boost-1.64.0

if [[ ! -d $USER_GIT_ROOT/boost ]]; then
    git clone --recursive git@github.com:boostorg/boost.git $USER_GIT_ROOT/boost
fi

cd $USER_GIT_ROOT/boost
git clean -fdx
git checkout --force "$BOOST_VER"
git submodule foreach 'git checkout --force "$BOOST_VER" || true'

./bootstrap.sh
./b2 --ignore-site-config \
     --prefix=$USER_GIT_ROOT/boost \
     -j$(nproc) \
     install

