#!/usr/bin/env zsh

WD=$USER_GIT_ROOT/binaryen
[[ ! -d $WD ]] && git clone git@github.com:WebAssembly/binaryen.git $WD

cd $WD
[[ $YES -eq 0 ]] && read REPLY"?clean $WD? [y|N] "
[[ $YES -eq 1 || $REPLY =~ ^[Yy]$ ]] && git clean -fdx
mkdir -p {build,release}
cd build

cmake \
    -DCMAKE_INSTALL_PREFIX=$WD/release \
    ..
make -j${NPROC:-1} install

