#!/usr/bin/env zsh

BOOST_VER=boost-1.64.0
WD=$USER_GIT_ROOT/boost
[[ ! -d $WD ]] && git clone \
                    --recursive \
                    --single-branch \
                    --branch "$BOOST_VER" \
                    git@github.com:boostorg/boost.git $WD

cd $WD
[[ $YES -eq 0 ]] && read REPLY"?clean $WD? [y|N] "
[[ $YES -eq 1 || $REPLY =~ ^[Yy]$ ]] && git clean -fdx
mkdir -p {build,release}

[[ $(uname) == "Linux" ]] && TOOLSET=gcc
[[ $(uname) == "FreeBSD" ]] && TOOLSET=clang
./bootstrap.sh \
    --with-toolset=$TOOLSET
./b2 \
    --ignore-site-config \
    -j${NPROC:-1} \
    --prefix=$WD/release \
    toolset=$TOOLSET \
    threading=multi \
    headers
./b2 \
    --ignore-site-config \
    -j${NPROC:-1} \
    --prefix=$WD/release \
    toolset=$TOOLSET \
    threading=multi \
    install

