#!/usr/bin/env zsh

WD=$USER_GIT_ROOT/secp256k1-zkp
if [[ ! -d $WD ]]; then
    git clone git@github.com:cryptonomex/secp256k1-zkp.git $WD
fi

cd $WD
read REPLY"?git clean $WD? [y|N] "
if [[ $REPLY =~ ^[Yy]$ ]]; then
    git clean -fdx
fi

./autogen.sh
./configure --prefix=$WD/release
gmake -j${NPROC:-1} install

