#!/usr/bin/env zsh

NPROC=$(getconf _NPROCESSORS_ONLN 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || echo 1)
export NPROC

[[ $USER_GIT_ROOT != "" ]] || read USER_GIT_ROOT"?\"Absolute path to clone required projects into(\$USER_GIT_ROOT)\"= "
[[ $USER_GIT_ROOT = /* ]] || { echo >&2 "error: not an absolute path."; exit 1 }
export USER_GIT_ROOT
mkdir -p $USER_GIT_ROOT || exit 1

YES=0
while getopts "y" OPTION; do
    case $OPTION in
        y)
            YES=1
    esac
done
export YES

[[ $YES -eq 0 ]] && read REPLY"?build secp256k1-zkp? [y|N] "
[[ $YES -eq 1 || $REPLY =~ ^[Yy]$ ]] && ./build_secp256k1-zkp
[[ $YES -eq 0 ]] && read REPLY"?build binaryen? [y|N] "
[[ $YES -eq 1 || $REPLY =~ ^[Yy]$ ]] && ./build_binaryen
[[ $YES -eq 0 ]] && read REPLY"?build boost? [y|N] "
[[ $YES -eq 1 || $REPLY =~ ^[Yy]$ ]] && ./build_boost
[[ $YES -eq 0 ]] && read REPLY"?build llvm? [y|N] "
[[ $YES -eq 1 || $REPLY =~ ^[Yy]$ ]] && ./build_llvm
[[ $YES -eq 0 ]] && read REPLY"?build eos? [y|N] "
[[ $YES -eq 1 || $REPLY =~ ^[Yy]$ ]] && ./build_eos

