#!/bin/zsh

if [[ ! -d $USER_GIT_ROOT/secp256k1-zkp ]]; then
    git clone git@github.com:cryptonomex/secp256k1-zkp.git $USER_GIT_ROOT/secp256k1-zkp
fi

cd $USER_GIT_ROOT/secp256k1-zkp
git clean -fdx
./autogen.sh
./configure --prefix=$USER_GIT_ROOT/secp256k1-zkp/release

make -j$(nproc) install

